# Generated by Django 4.0.5 on 2022-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo:')),
                ('contenido', models.TextField(verbose_name='Contenido:')),
                ('url', models.CharField(max_length=150, unique=True, verbose_name='URL:')),
                ('visibilidad', models.BooleanField(verbose_name='Visible:')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado:')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado:')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
            },
        ),
    ]
