# Generated by Django 4.0.5 on 2022-08-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='visibilidad',
            field=models.BooleanField(verbose_name='Visible'),
        ),
    ]
