# Generated by Django 4.0.5 on 2022-08-16 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0002_alter_pagina_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido:'),
        ),
    ]
