# Generated by Django 4.0.5 on 2022-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0003_alter_pagina_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden:'),
        ),
    ]
