# Generated by Django 4.0.5 on 2022-08-16 07:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion:')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado:')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo:')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(default='null', upload_to='', verbose_name='Imagen:')),
                ('publico', models.BooleanField(verbose_name='Publico')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado:')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado:')),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='Articulos.categoria', verbose_name='Categorias:')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario:')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
