# Generated by Django 4.0.5 on 2022-08-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='Articulos.categoria', verbose_name='Categorias:'),
        ),
    ]
